publish_to: none

name: qr_generator_reader
description: QR code generator and reader.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.5.2
  path_provider: ^2.0.2
  image_picker: ^0.8.2
  flutter_keyboard_visibility: ^5.0.3
  share: ^2.0.4
  permission_handler: ^8.1.4+1
  sqflite:
  path:
  intl: ^0.17.0
  fluttertoast: ^8.0.8

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-Regular.ttf
        - asset: assets/fonts/Exo2-ExtraBold.ttf
        - asset: assets/fonts/Exo2-Thin.ttf

          style: italic
    - family: AdventPro
      fonts:
        - asset: assets/fonts/AdventPro-Bold.ttf
        - asset: assets/fonts/AdventPro-Regular.ttf
          #weight: 700